---
title: "Trabajo 2. Operacionalización y visualización de datos"
subtitle: "R para análisis estadístico"
linktitle: "Trabajo 2. Operacionalización y visualización"
date: "2025-4-27"
lang: es
---

## Objetivos del trabajo

El objetivo de este trabajo es realizar un reporte dinámico a través de Quarto, que contenga el análisis descriptivo del problema de investigación propuesto en el Trabajo 1. El documento final debe ser subido a Github Pages y se debe enviar el link a este documento para su revisión.


## Instrucciones generales

- Descargar la base de datos que se utilizará en la investigación y guardarla en la carpeta correspondiente (input)
- Seleccionar un mínimo de 4 variables para, mediante su estudio, responder a la pregunta de investigación. Todas las variables deben remitir al tema de interés: 2 de las variables deben ser de nivel de medición de intervalo o razón, 1 variable debe ser de nivel de medición ordinal y 1 variable debe ser de nivel de medición nominal
- Seleccionar un conjunto de variables para armar una escala o índice.
- Para cada variable debe indicar: i) una breve descripción que especifique el nivel de medición de la  variable, su nombre en la base de datos y el fraseo en la encuesta, ii) explique qué aspecto del fenómeno de interés representa y iii) su utilidad para resolver la pregunta de investigación. La selección de variables debe ser coherente con la formulación del problema y la pregunta y objetivos de investigación propuestos.
- Operacionalización: Script de R llamado "Preparacion" y guardado en la carpeta que corresponde (Procesamiento). Manipulación de datos para obtener las variables utilizadas en la investigación. Se espera que l-s estudiantes sean capaces de seleccionar las variables relevantes para la problemática escogida, agruparlas, reordenarlas y asignarles los nombres y etiquetas según corresponda.
- Visualización de datos: Elaboración de tablas y/o gráficos, en el contexto de un reporte científico de investigación, que intente responder, ejemplificar y/o demostrar los principales hallazgos de la investigación. Para esta primera entrega se espera que sean capaces de generar una tabla descriptiva que muestre las medidas de tendencia central de las variables utilizadas en la investigación, así como su contraparte de tablas de frecuencias en el caso de variables categóricas. También se espera que sean capaces de elaborar dos gráficos descriptivos que permitan visualizar la distribución de las principales variables de interés.

- No es necesario elaborar un informe teórico sobre el tema de investigación. En la introducción de este reporte debe ir la propuesta elaborada en el Trabajo 1, pero es importante mencionar la fuente de datos utilizada. El objetivo del trabajo es que sean capaces de operacionalizar variables, escoger la mejor forma de visualizar sus medidas de tendencia central y/o frecuencias e **interpretar** estas tablas/gráficos.


Entrega:

- Lunes 27 de Abril a través de U-campus.
- Se debe enviar el link al repositorio de github y a Github Pages.
- No más de 3000 palabras
- Se deben mantener las referencias de la literatura / bases de datos revisadas (zotero)
- atrasos, 0,5 por día de atraso.

Rúbrica de evaluación:

| Ítem | Objetivo | Puntaje |
|------|----------|---------|
|1. Cargar base de datos        | L-s estudiantes son capaces de descargar la base de datos y posteriormente cargarla en R         |    2pts         |
|2. Selección de variables      | L-s estudiantes son capaces de seleccionar las variables relevantes según su problema de investigación   | 2pts        |
|3. Operacionalización de variables   | L-s estudiantes son capaces de operacionalizar correctamente las variables de interés. Las variables deben tener un correcto nivel de medición (2pto), correcto paso a NA (1pto), correcto orden de medición, es decir, valores positivos como valores más altos (1pto) y etiquetas correctas (1pto)          |     5pts    |
|4. Visualización de resultados       | L-s estudiantes son capaces de visualizar correctamente las variables de interés. Se espera que el reporte incluya una tabla descriptiva (2ptos) y dos gráficos univariados (3ptos)         |   5ptos      |
|5. Interpretación de resultados      | L-s estudiantes son capaces de interpretar correctamente las tablas y gráficos presentados       |  2pts       |
|6. Correcciones trabajo 1 | L-s estudiantes son capaces de incorporar las correcciones sugeridas en el trabajo 1         | 2pts        |
| Total|- |18puntos|

## Recomendaciones

- Para elaboración de tablas: [https://correlacional.netlify.app/assignment/06-practico](https://correlacional.netlify.app/assignment/06-practico)

- Para elaboración de gráficos: [https://correlacional.netlify.app/assignment/08-practico](https://correlacional.netlify.app/assignment/08-practico)

- Resumen unidad 1: [https://youtu.be/-pPmtz29vZ8?si=X4d1AvrSRe0UAs07](https://youtu.be/-pPmtz29vZ8?si=X4d1AvrSRe0UAs07)
